package lt.vu.usecases.mybatis.model;

public class University {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @return the value of PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @param id the value for PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @return the value of PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @param title the value for PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Mon May 14 20:35:20 EET 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }
}